version: '3.8'

services:

  db:
    image: mysql:latest
    container_name: erecipe_db
    environment:
      - MYSQL_DATABASE=erecipe_database
      - MYSQL_USER=django
      - MYSQL_PASSWORD=MYPASSWORD
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    networks:
      - erecipe_network
    healthcheck:
      test: "exit 0"
      retries: 3
      start_period: 10s
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: erecipe-backend
    networks:
      - erecipe_network
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=backend,localhost
      - DB_NAME=erecipe_database
      - DB_USER=django
      - DB_PASSWORD=MYPASSWORD
      - DB_HOST=db
      - DB_PORT=3306
    ports:
      - "81:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_DOMAIN: http://127.0.0.1
    container_name: erecipe-frontend
    networks:
      - erecipe_network
    ports:
      - "80:80"
    depends_on:
      - backend

networks:
  erecipe_network:
    driver: bridge

volumes:
  mysql_data:
